#!/usr/bin/env python
import speech_recognition as sr
import inout.speech as speech
import inout.ears as ears
import settings
import time
import os
import sys

def start_assistant() :
    r = sr.Recognizer()
    r.energy_threshold = 800
    r.dynamic_energy_threshold = True

    ret = os.system("jack_control start")
    if(ret):
        exit(2)

    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source)

    stop_listening = r.listen_in_background(source, ears.listen)
    print(cfg)
    print("\nHello, I'm listening :)")

    while True:
        time.sleep(10)

settings.load_config()
cfg = settings.cfg
start_assistant()
