#!/usr/bin/env python

# >>> automatos <<<

import speech_recognition as sr
import inout.speech as speech
import inout.ears as ears
import settings
import time
import os
import sys

def start_assistant() :
    r = sr.Recognizer()
    r.dynamic_energy_threshold = True

    ret = os.system("jack_control start")
    if(ret):
        exit(2)

    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source)

    #speech.greeting()

    stop_listening = r.listen_in_background(source, ears.listen)

    while True:
        msg = sys.stdin.readline()
        speech.read_text(msg)

settings.config()
start_assistant()
